extensions = [
  "adpyke.vscode-sql-formatter",
  "bierner.markdown-mermaid",
  "dbaeumer.vscode-eslint",
  "deerawan.vscode-dash",
  "editorconfig.editorconfig",
  "hoovercj.vscode-power-mode",
  "mechatroner.rainbow-csv",
  "redhat.vscode-yaml",
  "richie5um2.vscode-sort-json",
  "tamasfe.even-better-toml",
  "wakatime.vscode-wakatime",
  # shell
  "bmalehorn.vscode-fish",
  "foxundermoon.shell-format",
  # docker
  "ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers",
  # css
  "bradlc.vscode-tailwindcss",
  "csstools.postcss",
  # github
  "github.copilot",
  "github.copilot-chat",
  "github.vscode-github-actions",
  # git
  "donjayamanne.githistory",
  "letmaik.git-tree-compare",
  "waderyan.gitblame",
  # elixir
  "jakebecker.elixir-ls",
  "jamilabreu.vscode-phoenix-snippets",
  "pantajoe.vscode-elixir-credo",
  "phoenix-liveview-snippets.phoenix-liveview-snippets",
  "phoenixframework.phoenix",
  "samuel-pordeus.elixir-test",
  # haskell
  "haskell.haskell",
  # nix
  "jnoortheen.nix-ide",
  # rust
  "a5huynh.vscode-ron",
  "rust-lang.rust-analyzer",
]
