version: "3"

includes:
  brew: ./taskfiles/brew.yml
  chezmoi: ./taskfiles/chezmoi.yml
  defaults: ./taskfiles/defaults.yml
  devbox: ./taskfiles/devbox.yml
  git: ./taskfiles/git.yml
  install: ./taskfiles/install.yml
  mise: ./taskfiles/mise.yml
  vscode: ./taskfiles/vscode.yml

tasks:
  setup:
    deps:
      - install:rosetta
      - devbox:pull
    cmds:
      - task: install:omf
      - task: chezmoi:apply
      - task: install:brew
      - task: brew:bundle
      - task: mise:install
      - task: defaults:import-all
      - task: defaults:setup

  watch:
    aliases: [w]
    deps:
      - task: git:watch
        vars:
          DIR: ~/fireworks/subnote/para
    watch: true

  push:
    aliases: [p]
    deps:
      - task: git:push
        vars:
          DIR: ~/fireworks/subnote

  auto-commit:
    aliases: [ac]
    deps:
      - task: git:auto-commit
        vars:
          DIR: ~/fireworks/para
