version: "3"

includes:
  brew: ./taskfiles/brew.yml
  chezmoi: ./taskfiles/chezmoi.yml
  defaults: ./taskfiles/defaults.yml
  devbox: ./taskfiles/devbox.yml
  git: ./taskfiles/git.yml
  setup: ./taskfiles/setup.yml
  mise: ./taskfiles/mise.yml
  vscode: ./taskfiles/vscode.yml

tasks:
  setup:
    deps:
      - setup:rosetta
      - devbox:pull
    cmds:
      - task: chezmoi:apply
      - task: setup:brew
      # - task: setup:chsh
      - task: setup:omf
      - task: brew:bundle
      - task: mise:install
      - task: defaults:import-all
      - task: defaults:setup

  watch:
    aliases: [w]
    deps:
      - task: git:watch
        vars:
          DIR: ~/fireworks/subnote/para
    watch: true

  push:
    aliases: [pf]
    deps:
      - task: git:push-force
        vars:
          DIR: ~/fireworks/para

  auto-commit:
    aliases: [ac]
    deps:
      - task: git:auto-commit
        vars:
          DIR: ~/fireworks/para
